[package]
name = "nonogram-solver"
version = "0.1.0"
authors = ["Simon Frankau <sgf@arbitrary.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.0.1"